name: SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # necessario per SonarCloud

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # The SonarCloud analysis step below has been removed/commented out
      # - name: Run SonarCloud analysis
      #   run: mvn sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}